# Generated by Django 5.0.6 on 2024-07-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='houselistingModel',
            new_name='listing',
        ),
    ]
